services:
  mysql:
    image: mysql:9.2
    container_name: commerce-mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: commerce
      MYSQL_USER: commerce_user
      MYSQL_PASSWORD: commerce1234
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234"]
      timeout: 20s
      retries: 10
      interval: 30s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/mysql/01-schema-mysql.sql:/docker-entrypoint-initdb.d/01-schema-mysql.sql
      - ./data/mysql/02-tables-mysql.sql:/docker-entrypoint-initdb.d/02-tables-mysql.sql
      - ./data/mysql/03-products-init.sql:/docker-entrypoint-initdb.d/03-products-init.sql
    networks:
      - commerce-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  commerce-network:
    driver: bridge