services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3310:3306"
    env_file:
      - ./data/mysql/env.mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - data:/var/lib/mysql
      - ./data/mysql/01-schema-mysql.sql:/docker-entrypoint-initdb.d/01-schema-mysql.sql
      - ./data/mysql/02-tables-mysql.sql:/docker-entrypoint-initdb.d/02-tables-mysql.sql
      - ./data/mysql/03-products-init.sql:/docker-entrypoint-initdb.d/03-products-init.sql
    networks:
      - network

volumes:
  data:

networks:
  network: